#pragma once

/*
   -- Audio Biometric --

   To compile this code using RemoteXY library 4.1.4 or later version
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;

   To interact with the GUI, please refer to the manual:
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and
   is an example for the RemoteXY library.
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license
   details.
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
// #define REMOTEXY__DEBUGLOG

// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

#ifndef REMOTEXY_BLUETOOTH_NAME
// RemoteXY connection settings
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY"
#endif

#include <RemoteXY.h>

#define USE_REALTIME_RECORDING 1

// RemoteXY GUI configuration
#pragma pack(push, 1)
inline uint8_t RemoteXY_CONF[] = // 828 bytes
#if USE_REALTIME_RECORDING == 0
    {255, 158, 0, 148, 1, 53, 3, 19, 0, 0, 0, 66, 105, 111, 109, 101, 116, 114, 105, 99,
     0, 31, 1, 106, 200, 3, 1, 0, 0, 19, 0, 130, 7, 19, 91, 66, 27, 16, 1, 27,
     92, 52, 52, 0, 38, 31, 82, 101, 107, 97, 109, 0, 131, 27, 181, 16, 17, 1, 16, 125,
     31, 240, 159, 142, 181, 0, 38, 129, 18, 161, 71, 6, 64, 29, 82, 101, 107, 97, 109, 97,
     110, 32, 98, 101, 114, 100, 117, 114, 97, 115, 105, 32, 53, 32, 100, 101, 116, 105, 107, 0,
     70, 83, 90, 12, 12, 16, 26, 37, 0, 129, 14, 59, 36, 5, 64, 210, 80, 101, 114, 105,
     110, 116, 97, 104, 32, 83, 105, 115, 116, 101, 109, 0, 129, 14, 47, 19, 5, 64, 210, 80,
     101, 114, 105, 110, 116, 97, 104, 0, 67, 22, 151, 60, 6, 101, 27, 16, 65, 67, 14, 64,
     79, 6, 68, 213, 16, 65, 67, 14, 52, 79, 6, 68, 213, 16, 33, 67, 14, 40, 79, 6,
     68, 213, 16, 11, 67, 14, 28, 79, 6, 68, 213, 16, 33, 129, 34, 7, 37, 8, 64, 213,
     86, 101, 114, 105, 102, 105, 107, 97, 116, 111, 114, 0, 129, 14, 35, 25, 5, 64, 210, 75,
     101, 99, 111, 99, 111, 107, 97, 110, 0, 129, 14, 23, 15, 5, 64, 210, 83, 116, 97, 116,
     117, 115, 0, 131, 45, 181, 16, 17, 1, 16, 209, 31, 240, 159, 142, 153, 239, 184, 143, 0,
     41, 131, 63, 181, 16, 17, 1, 16, 97, 31, 226, 154, 153, 239, 184, 143, 0, 26, 129, 14,
     71, 35, 5, 64, 210, 82, 101, 102, 101, 114, 101, 110, 115, 105, 32, 83, 117, 97, 114, 97,
     0, 67, 14, 76, 79, 6, 68, 213, 16, 65, 12, 0, 130, 7, 19, 91, 66, 27, 16, 7,
     14, 52, 79, 11, 36, 64, 26, 30, 156, 21, 129, 14, 36, 44, 6, 64, 141, 73, 115, 105,
     32, 110, 97, 109, 97, 32, 115, 97, 109, 112, 101, 108, 0, 129, 14, 43, 71, 6, 64, 141,
     115, 101, 98, 101, 108, 117, 109, 32, 109, 101, 110, 103, 97, 109, 98, 105, 108, 32, 115, 117,
     97, 114, 97, 0, 1, 27, 92, 52, 52, 0, 38, 31, 65, 109, 98, 105, 108, 32, 83, 97,
     109, 112, 101, 108, 0, 129, 19, 161, 66, 6, 64, 29, 83, 97, 109, 112, 101, 108, 32, 98,
     101, 114, 100, 117, 114, 97, 115, 105, 32, 53, 32, 100, 101, 116, 105, 107, 0, 70, 83, 90,
     12, 12, 16, 26, 37, 0, 67, 22, 151, 60, 6, 101, 27, 16, 65, 129, 28, 7, 50, 8,
     64, 143, 83, 97, 109, 112, 101, 108, 32, 83, 117, 97, 114, 97, 0, 131, 27, 181, 16, 17,
     1, 16, 125, 31, 240, 159, 142, 181, 0, 38, 131, 45, 181, 16, 17, 1, 16, 209, 31, 240,
     159, 142, 153, 239, 184, 143, 0, 41, 131, 63, 181, 16, 17, 1, 16, 97, 31, 226, 154, 153,
     239, 184, 143, 0, 26, 20, 0, 129, 17, 7, 72, 8, 64, 100, 80, 101, 110, 103, 97, 116,
     117, 114, 97, 110, 32, 75, 111, 110, 101, 107, 115, 105, 0, 130, 7, 76, 91, 63, 27, 16,
     129, 13, 81, 20, 7, 64, 101, 77, 81, 84, 84, 0, 129, 13, 92, 61, 5, 64, 99, 72,
     111, 115, 116, 110, 97, 109, 101, 32, 97, 116, 97, 117, 32, 73, 80, 32, 65, 100, 100, 114,
     101, 115, 115, 58, 0, 7, 13, 97, 79, 9, 36, 64, 87, 30, 2, 33, 2, 69, 127, 23,
     7, 0, 2, 26, 31, 31, 79, 78, 0, 79, 70, 70, 0, 129, 13, 108, 10, 5, 64, 99,
     80, 111, 114, 116, 0, 7, 13, 113, 79, 9, 52, 64, 87, 30, 2, 129, 13, 128, 30, 5,
     64, 99, 71, 117, 110, 97, 107, 97, 110, 32, 83, 83, 76, 0, 130, 7, 20, 91, 52, 27,
     16, 129, 12, 25, 14, 7, 64, 101, 87, 73, 70, 73, 0, 129, 13, 36, 11, 5, 64, 99,
     83, 83, 73, 68, 0, 7, 13, 41, 80, 9, 36, 64, 87, 30, 2, 33, 129, 13, 52, 23,
     5, 64, 99, 80, 97, 115, 115, 119, 111, 114, 100, 0, 7, 13, 57, 80, 9, 36, 64, 87,
     30, 2, 65, 131, 27, 181, 16, 17, 1, 16, 125, 31, 240, 159, 142, 181, 0, 38, 131, 45,
     181, 16, 17, 1, 16, 209, 31, 240, 159, 142, 153, 239, 184, 143, 0, 41, 131, 63, 181, 16,
     17, 1, 16, 97, 31, 226, 154, 153, 239, 184, 143, 0, 26, 1, 21, 156, 65, 18, 1, 84,
     87, 83, 105, 109, 112, 97, 110, 32, 80, 101, 110, 103, 97, 116, 117, 114, 97, 110, 0, 67,
     14, 145, 80, 6, 101, 27, 16, 65};
#else
    {255, 157, 0, 87, 1, 12, 3, 19, 0, 0, 0, 66, 105, 111, 109, 101, 116, 114, 105, 99,
     0, 31, 1, 106, 200, 3, 1, 0, 0, 18, 0, 130, 7, 85, 92, 93, 27, 209, 130, 7,
     19, 92, 66, 27, 16, 131, 27, 181, 16, 17, 1, 16, 125, 31, 240, 159, 142, 181, 0, 38,
     129, 14, 59, 36, 5, 64, 210, 80, 101, 114, 105, 110, 116, 97, 104, 32, 83, 105, 115, 116,
     101, 109, 0, 129, 14, 47, 19, 5, 64, 210, 80, 101, 114, 105, 110, 116, 97, 104, 0, 67,
     14, 64, 79, 6, 68, 213, 16, 65, 67, 14, 52, 79, 6, 68, 213, 16, 33, 67, 14, 40,
     79, 6, 68, 213, 16, 11, 67, 14, 28, 79, 6, 68, 213, 16, 33, 129, 34, 7, 37, 8,
     64, 213, 86, 101, 114, 105, 102, 105, 107, 97, 116, 111, 114, 0, 129, 14, 35, 25, 5, 64,
     210, 75, 101, 99, 111, 99, 111, 107, 97, 110, 0, 129, 14, 23, 15, 5, 64, 210, 83, 116,
     97, 116, 117, 115, 0, 131, 45, 181, 16, 17, 1, 16, 209, 31, 240, 159, 142, 153, 239, 184,
     143, 0, 41, 131, 63, 181, 16, 17, 1, 16, 97, 31, 226, 154, 153, 239, 184, 143, 0, 26,
     129, 14, 71, 35, 5, 64, 210, 82, 101, 102, 101, 114, 101, 110, 115, 105, 32, 83, 117, 97,
     114, 97, 0, 67, 14, 76, 79, 6, 68, 213, 16, 65, 68, 10, 88, 86, 87, 17, 213, 209,
     70, 84, 22, 12, 12, 16, 26, 37, 0, 12, 0, 130, 7, 19, 91, 66, 27, 16, 7, 14,
     52, 79, 11, 36, 64, 26, 30, 156, 21, 129, 14, 36, 44, 6, 64, 141, 73, 115, 105, 32,
     110, 97, 109, 97, 32, 115, 97, 109, 112, 101, 108, 0, 129, 14, 43, 71, 6, 64, 141, 115,
     101, 98, 101, 108, 117, 109, 32, 109, 101, 110, 103, 97, 109, 98, 105, 108, 32, 115, 117, 97,
     114, 97, 0, 1, 27, 92, 52, 52, 0, 38, 31, 65, 109, 98, 105, 108, 32, 83, 97, 109,
     112, 101, 108, 0, 129, 19, 161, 66, 6, 64, 29, 83, 97, 109, 112, 101, 108, 32, 98, 101,
     114, 100, 117, 114, 97, 115, 105, 32, 53, 32, 100, 101, 116, 105, 107, 0, 70, 83, 90, 12,
     12, 16, 26, 37, 0, 67, 22, 151, 60, 6, 101, 27, 16, 65, 129, 28, 7, 50, 8, 64,
     143, 83, 97, 109, 112, 101, 108, 32, 83, 117, 97, 114, 97, 0, 131, 27, 181, 16, 17, 1,
     16, 125, 31, 240, 159, 142, 181, 0, 38, 131, 45, 181, 16, 17, 1, 16, 209, 31, 240, 159,
     142, 153, 239, 184, 143, 0, 41, 131, 63, 181, 16, 17, 1, 16, 97, 31, 226, 154, 153, 239,
     184, 143, 0, 26, 20, 0, 129, 17, 7, 72, 8, 64, 100, 80, 101, 110, 103, 97, 116, 117,
     114, 97, 110, 32, 75, 111, 110, 101, 107, 115, 105, 0, 130, 7, 76, 91, 63, 27, 16, 129,
     13, 81, 20, 7, 64, 101, 77, 81, 84, 84, 0, 129, 13, 92, 61, 5, 64, 99, 72, 111,
     115, 116, 110, 97, 109, 101, 32, 97, 116, 97, 117, 32, 73, 80, 32, 65, 100, 100, 114, 101,
     115, 115, 58, 0, 7, 13, 97, 79, 9, 36, 64, 87, 30, 2, 33, 2, 69, 127, 23, 7,
     0, 2, 26, 31, 31, 79, 78, 0, 79, 70, 70, 0, 129, 13, 108, 10, 5, 64, 99, 80,
     111, 114, 116, 0, 7, 13, 113, 79, 9, 52, 64, 87, 30, 2, 129, 13, 128, 30, 5, 64,
     99, 71, 117, 110, 97, 107, 97, 110, 32, 83, 83, 76, 0, 130, 7, 20, 91, 52, 27, 16,
     129, 12, 25, 14, 7, 64, 101, 87, 73, 70, 73, 0, 129, 13, 36, 11, 5, 64, 99, 83,
     83, 73, 68, 0, 7, 13, 41, 80, 9, 36, 64, 87, 30, 2, 33, 129, 13, 52, 23, 5,
     64, 99, 80, 97, 115, 115, 119, 111, 114, 100, 0, 7, 13, 57, 80, 9, 36, 64, 87, 30,
     2, 65, 131, 27, 181, 16, 17, 1, 16, 125, 31, 240, 159, 142, 181, 0, 38, 131, 45, 181,
     16, 17, 1, 16, 209, 31, 240, 159, 142, 153, 239, 184, 143, 0, 41, 131, 63, 181, 16, 17,
     1, 16, 97, 31, 226, 154, 153, 239, 184, 143, 0, 26, 1, 21, 156, 65, 18, 1, 84, 87,
     83, 105, 109, 112, 97, 110, 32, 80, 101, 110, 103, 97, 116, 117, 114, 97, 110, 0, 67, 14,
     145, 80, 6, 101, 27, 16, 65};
#endif

// this structure defines all the variables and events of your control interface
struct RemoteXY_t
{

#if USE_REALTIME_RECORDING == 0
  // input variables
  uint8_t button_recorder;      // =1 if button pressed, else =0, from 0 to 1
  char input_voice_name[21];    // string UTF8 end zero
  uint8_t button_sampler;       // =1 if button pressed, else =0, from 0 to 1
  char input_mqtt_host[33];     // string UTF8 end zero
  uint8_t input_mqtt_use_ssl;   // =1 if switch ON and =0 if OFF, from 0 to 1
  int16_t input_mqtt_port;      // -32768 .. +32767
  char input_wifi_ssid[33];     // string UTF8 end zero
  char input_wifi_password[65]; // string UTF8 end zero
  uint8_t button_store_config;  // =1 if button pressed, else =0, from 0 to 1

  // output variables
  uint8_t led_recorder;                      // from 0 to 1
  char value_recorder_status[65];            // string UTF8 end zero
  char value_recorder_command[65];           // string UTF8 end zero
  char value_recorder_transcription[33];     // string UTF8 end zero
  char value_recorder_similarity_status[11]; // string UTF8 end zero
  char value_recorder_verified_status[33];   // string UTF8 end zero
  char value_recorder_reference[65];         // string UTF8 end zero
  uint8_t led_sampler;                       // from 0 to 1
  char value_sampler_status[65];             // string UTF8 end zero
  char value_config_status[65];              // string UTF8 end zero

  // other variable
  uint8_t connect_flag; // =1 if wire connected, else =0
#else
  // input variables
  char input_voice_name[21];    // string UTF8 end zero
  uint8_t button_sampler;       // =1 if button pressed, else =0, from 0 to 1
  char input_mqtt_host[33];     // string UTF8 end zero
  uint8_t input_mqtt_use_ssl;   // =1 if switch ON and =0 if OFF, from 0 to 1
  int16_t input_mqtt_port;      // -32768 .. +32767
  char input_wifi_ssid[33];     // string UTF8 end zero
  char input_wifi_password[65]; // string UTF8 end zero
  uint8_t button_store_config;  // =1 if button pressed, else =0, from 0 to 1

  // output variables
  char value_recorder_command[65];           // string UTF8 end zero
  char value_recorder_transcription[33];     // string UTF8 end zero
  char value_recorder_similarity_status[11]; // string UTF8 end zero
  char value_recorder_verified_status[33];   // string UTF8 end zero
  char value_recorder_reference[65];         // string UTF8 end zero
  float recorder_peak_graph;
  uint8_t led_recorder;          // from 0 to 1
  uint8_t led_sampler;           // from 0 to 1
  char value_sampler_status[65]; // string UTF8 end zero
  char value_config_status[65];  // string UTF8 end zero

  // other variable
  uint8_t connect_flag; // =1 if wire connected, else =0
#endif
};
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

inline RemoteXY_t RemoteXY;